[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "node server/index.js"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[[services]]
name = "web"